/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hidevopsio/mioclient/pkg/apis/mio/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GatewayConfigLister helps list GatewayConfigs.
type GatewayConfigLister interface {
	// List lists all GatewayConfigs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.GatewayConfig, err error)
	// GatewayConfigs returns an object that can list and get GatewayConfigs.
	GatewayConfigs(namespace string) GatewayConfigNamespaceLister
	GatewayConfigListerExpansion
}

// gatewayConfigLister implements the GatewayConfigLister interface.
type gatewayConfigLister struct {
	indexer cache.Indexer
}

// NewGatewayConfigLister returns a new GatewayConfigLister.
func NewGatewayConfigLister(indexer cache.Indexer) GatewayConfigLister {
	return &gatewayConfigLister{indexer: indexer}
}

// List lists all GatewayConfigs in the indexer.
func (s *gatewayConfigLister) List(selector labels.Selector) (ret []*v1alpha1.GatewayConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GatewayConfig))
	})
	return ret, err
}

// GatewayConfigs returns an object that can list and get GatewayConfigs.
func (s *gatewayConfigLister) GatewayConfigs(namespace string) GatewayConfigNamespaceLister {
	return gatewayConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GatewayConfigNamespaceLister helps list and get GatewayConfigs.
type GatewayConfigNamespaceLister interface {
	// List lists all GatewayConfigs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.GatewayConfig, err error)
	// Get retrieves the GatewayConfig from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.GatewayConfig, error)
	GatewayConfigNamespaceListerExpansion
}

// gatewayConfigNamespaceLister implements the GatewayConfigNamespaceLister
// interface.
type gatewayConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GatewayConfigs in the indexer for a given namespace.
func (s gatewayConfigNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.GatewayConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GatewayConfig))
	})
	return ret, err
}

// Get retrieves the GatewayConfig from the indexer for a given namespace and name.
func (s gatewayConfigNamespaceLister) Get(name string) (*v1alpha1.GatewayConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("gatewayconfig"), name)
	}
	return obj.(*v1alpha1.GatewayConfig), nil
}
