apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.mio.io
spec:
  group: mio.io
  version: v1alpha1
  names:
    kind: Build
    plural: builds
  scope: Namespaced