apiVersion: mio.io/v1alpha1
kind: BuildConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mio.io/v1alpha1","kind":"BuildConfig","metadata":{"annotations":{},"clusterName":"","creationTimestamp":"2018-10-23T08:29:45Z","generation":0,"name":"java","namespace":"templates","resourceVersion":"108849568","selfLink":"/apis/mio.io/v1alpha1/namespaces/templates/buildconfigs/java","uid":"cbfe8ba0-d69d-11e8-a640-005056935c80"},"spec":{"app":"","baseImage":"docker.vpclub.cn/hidevopsio/hinode-java-jar:1.21","cloneConfig":{"branch":"master","dstDir":"/opt/app-root/src/vpclub","password":"","url":"https://gitlab.vpclub.cn","username":""},"cloneType":"","codeType":"java","compileCmd":[{"commandName":"pwd"},{"Script":"mvn clean package -U -Dmaven.test.skip=true -Djava.net.preferIPv4Stack=true\nif [[ $? == 0 ]]; then\n  echo 'Build Successful.'\nelse\n  echo 'Build Failed!'\n  exit 1\nfi","execType":"script"},{"commandName":"pwd"},{"Script":"ls","execType":"script"}],"deployData":{"Envs":{"CODE_TYPE":"java","DOCKER_API_VERSION":"1.24","MAVEN_MIRROR_URL":"http://nexus.vpclub.cn/repository/maven-public/","OCDE_TYPE":"java"},"HostPathVolume":{"/var/lib/docker":"/var/lib/docker","/var/run/docker.sock":"/var/run/docker.sock"},"Ports":[8080,7575],"Replicas":1},"dockerFile":["FROM clarechu/base-image-java:0.1","ENV  TZ=\"Asia/Shanghai\"","ENV  APP_OPTIONS=\"-Xms128m -Xmx512m -Xss512k\"","ENV   APP_OPTIONS=\"-Xms128m -Xmx512m -Xss512k\"","USER 0","RUN  useradd -u 1002 -r -g 0 -d ${HOME} -s /sbin/nologin -c \"Default Application User\" java","COPY ./app.jar ${HOME}","RUN chown -R 1001:0 ${HOME}","USER 1002","EXPOSE 8080","EXPOSE 7575","ENTRYPOINT [\"sh\",\"-c\",\"java -jar $HOME/app.jar $APP_OPTIONS\"]"],"dockerRegistry":"docker-registry-default.app.vpclub.io","events":["createService","deployNode","clone","compile","buildImage","pushImage","deleteDeployment"],"nodeService":""},"status":{"lastVersion":1}}
  clusterName: ""
  creationTimestamp: 2018-10-23T08:29:45Z
  generation: 0
  name: java
  namespace: templates
  resourceVersion: "125861589"
  selfLink: /apis/mio.io/v1alpha1/namespaces/templates/buildconfigs/java
  uid: cbfe8ba0-d69d-11e8-a640-005056935c80
spec:
  app: ""
  baseImage: docker.vpclub.cn/hidevopsio/hinode-java-jar:1.22
  cloneConfig:
    branch: development
    dstDir: /opt/app-root/src/vpclub
    password: ""
    url: https://gitlab.vpclub.cn
    username: ""
  cloneType: ""
  codeType: java
  compileCmd:
  - commandName: pwd
  - Script: |-
      mvn clean package -U -Dmaven.test.skip=true -Djava.net.preferIPv4Stack=true
      if [[ $? == 0 ]]; then
        echo 'Build Successful.'
      else
        echo 'Build Failed!'
        exit 1
      fi
    execType: script
  - commandName: pwd
  - Script: ls
    execType: script
  deployData:
    envs:
      CODE_TYPE: java
      DOCKER_API_VERSION: "1.24"
      MAVEN_MIRROR_URL: http://nexus.vpclub.cn/repository/maven-public/
    hostPathVolume:
      /var/lib/docker: /var/lib/docker
      /var/run/docker.sock: /var/run/docker.sock
    ports:
    - 8080
    - 7575
    replicas: 1
  dockerAuthConfig:
    password: aa
    username: unused
  dockerFile:
  - FROM clarechu/base-image-java:0.1
  - ENV  TZ="Asia/Shanghai"
  - ENV  APP_OPTIONS="-Xms128m -Xmx512m -Xss512k"
  - ENV   APP_OPTIONS="-Xms128m -Xmx512m -Xss512k"
  - USER 0
  - RUN  useradd -u 1002 -r -g 0 -d ${HOME} -s /sbin/nologin -c "Default Application
    User" java
  - COPY ./app.jar ${HOME}
  - RUN chown -R 1001:0 ${HOME}
  - USER 1002
  - EXPOSE 8080
  - EXPOSE 7575
  - ENTRYPOINT ["sh","-c","java -jar $HOME/app.jar $APP_OPTIONS"]
  dockerRegistry: docker-registry-default.app.vpclub.io
  nodeService: ""
  tasks:
  - name: createService
  - name: deployNode
  - name: clone
  - name: compile
  - name: buildImage
  - name: pushImage
  - name: deleteDeployment
status:
  lastVersion: 1
