apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testconfigs.mio.io
spec:
  group: mio.io
  version: v1alpha1
  names:
    kind: TestConfig
    plural: testconfigs
  scope: Namespaced