/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "hidevops.io/mioclient/pkg/apis/mio/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTestConfigs implements TestConfigInterface
type FakeTestConfigs struct {
	Fake *FakeMioV1alpha1
	ns   string
}

var testconfigsResource = schema.GroupVersionResource{Group: "mio.io", Version: "v1alpha1", Resource: "testconfigs"}

var testconfigsKind = schema.GroupVersionKind{Group: "mio.io", Version: "v1alpha1", Kind: "TestConfig"}

// Get takes name of the testConfig, and returns the corresponding testConfig object, and an error if there is any.
func (c *FakeTestConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.TestConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testconfigsResource, c.ns, name), &v1alpha1.TestConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestConfig), err
}

// List takes label and field selectors, and returns the list of TestConfigs that match those selectors.
func (c *FakeTestConfigs) List(opts v1.ListOptions) (result *v1alpha1.TestConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testconfigsResource, testconfigsKind, c.ns, opts), &v1alpha1.TestConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TestConfigList{}
	for _, item := range obj.(*v1alpha1.TestConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested testConfigs.
func (c *FakeTestConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testconfigsResource, c.ns, opts))

}

// Create takes the representation of a testConfig and creates it.  Returns the server's representation of the testConfig, and an error, if there is any.
func (c *FakeTestConfigs) Create(testConfig *v1alpha1.TestConfig) (result *v1alpha1.TestConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testconfigsResource, c.ns, testConfig), &v1alpha1.TestConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestConfig), err
}

// Update takes the representation of a testConfig and updates it. Returns the server's representation of the testConfig, and an error, if there is any.
func (c *FakeTestConfigs) Update(testConfig *v1alpha1.TestConfig) (result *v1alpha1.TestConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testconfigsResource, c.ns, testConfig), &v1alpha1.TestConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTestConfigs) UpdateStatus(testConfig *v1alpha1.TestConfig) (*v1alpha1.TestConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(testconfigsResource, "status", c.ns, testConfig), &v1alpha1.TestConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestConfig), err
}

// Delete takes name of the testConfig and deletes it. Returns an error if one occurs.
func (c *FakeTestConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(testconfigsResource, c.ns, name), &v1alpha1.TestConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTestConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TestConfigList{})
	return err
}

// Patch applies the patch and returns the patched testConfig.
func (c *FakeTestConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testconfigsResource, c.ns, name, data, subresources...), &v1alpha1.TestConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestConfig), err
}
