/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hidevopsio/mioclient/pkg/apis/mio/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSourceConfigs implements SourceConfigInterface
type FakeSourceConfigs struct {
	Fake *FakeMioV1alpha1
	ns   string
}

var sourceconfigsResource = schema.GroupVersionResource{Group: "mio.k8s.io", Version: "v1alpha1", Resource: "sourceconfigs"}

var sourceconfigsKind = schema.GroupVersionKind{Group: "mio.k8s.io", Version: "v1alpha1", Kind: "SourceConfig"}

// Get takes name of the sourceConfig, and returns the corresponding sourceConfig object, and an error if there is any.
func (c *FakeSourceConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.SourceConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sourceconfigsResource, c.ns, name), &v1alpha1.SourceConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceConfig), err
}

// List takes label and field selectors, and returns the list of SourceConfigs that match those selectors.
func (c *FakeSourceConfigs) List(opts v1.ListOptions) (result *v1alpha1.SourceConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sourceconfigsResource, sourceconfigsKind, c.ns, opts), &v1alpha1.SourceConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SourceConfigList{}
	for _, item := range obj.(*v1alpha1.SourceConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sourceConfigs.
func (c *FakeSourceConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sourceconfigsResource, c.ns, opts))

}

// Create takes the representation of a sourceConfig and creates it.  Returns the server's representation of the sourceConfig, and an error, if there is any.
func (c *FakeSourceConfigs) Create(sourceConfig *v1alpha1.SourceConfig) (result *v1alpha1.SourceConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sourceconfigsResource, c.ns, sourceConfig), &v1alpha1.SourceConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceConfig), err
}

// Update takes the representation of a sourceConfig and updates it. Returns the server's representation of the sourceConfig, and an error, if there is any.
func (c *FakeSourceConfigs) Update(sourceConfig *v1alpha1.SourceConfig) (result *v1alpha1.SourceConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sourceconfigsResource, c.ns, sourceConfig), &v1alpha1.SourceConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSourceConfigs) UpdateStatus(sourceConfig *v1alpha1.SourceConfig) (*v1alpha1.SourceConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sourceconfigsResource, "status", c.ns, sourceConfig), &v1alpha1.SourceConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceConfig), err
}

// Delete takes name of the sourceConfig and deletes it. Returns an error if one occurs.
func (c *FakeSourceConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sourceconfigsResource, c.ns, name), &v1alpha1.SourceConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSourceConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sourceconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SourceConfigList{})
	return err
}

// Patch applies the patch and returns the patched sourceConfig.
func (c *FakeSourceConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SourceConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sourceconfigsResource, c.ns, name, data, subresources...), &v1alpha1.SourceConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SourceConfig), err
}
