/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "hidevops.io/mioclient/pkg/apis/mio/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNotifies implements NotifyInterface
type FakeNotifies struct {
	Fake *FakeMioV1alpha1
	ns   string
}

var notifiesResource = schema.GroupVersionResource{Group: "mio.io", Version: "v1alpha1", Resource: "notifies"}

var notifiesKind = schema.GroupVersionKind{Group: "mio.io", Version: "v1alpha1", Kind: "Notify"}

// Get takes name of the notify, and returns the corresponding notify object, and an error if there is any.
func (c *FakeNotifies) Get(name string, options v1.GetOptions) (result *v1alpha1.Notify, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(notifiesResource, c.ns, name), &v1alpha1.Notify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notify), err
}

// List takes label and field selectors, and returns the list of Notifies that match those selectors.
func (c *FakeNotifies) List(opts v1.ListOptions) (result *v1alpha1.NotifyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(notifiesResource, notifiesKind, c.ns, opts), &v1alpha1.NotifyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NotifyList{}
	for _, item := range obj.(*v1alpha1.NotifyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested notifies.
func (c *FakeNotifies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(notifiesResource, c.ns, opts))

}

// Create takes the representation of a notify and creates it.  Returns the server's representation of the notify, and an error, if there is any.
func (c *FakeNotifies) Create(notify *v1alpha1.Notify) (result *v1alpha1.Notify, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(notifiesResource, c.ns, notify), &v1alpha1.Notify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notify), err
}

// Update takes the representation of a notify and updates it. Returns the server's representation of the notify, and an error, if there is any.
func (c *FakeNotifies) Update(notify *v1alpha1.Notify) (result *v1alpha1.Notify, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(notifiesResource, c.ns, notify), &v1alpha1.Notify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notify), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNotifies) UpdateStatus(notify *v1alpha1.Notify) (*v1alpha1.Notify, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(notifiesResource, "status", c.ns, notify), &v1alpha1.Notify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notify), err
}

// Delete takes name of the notify and deletes it. Returns an error if one occurs.
func (c *FakeNotifies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(notifiesResource, c.ns, name), &v1alpha1.Notify{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNotifies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(notifiesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NotifyList{})
	return err
}

// Patch applies the patch and returns the patched notify.
func (c *FakeNotifies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Notify, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(notifiesResource, c.ns, name, data, subresources...), &v1alpha1.Notify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notify), err
}
