/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "hidevops.io/mioclient/pkg/apis/mio/v1alpha1"
	scheme "hidevops.io/mioclient/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TestsesGetter has a method to return a TestsInterface.
// A group's client should implement this interface.
type TestsesGetter interface {
	Testses(namespace string) TestsInterface
}

// TestsInterface has methods to work with Tests resources.
type TestsInterface interface {
	Create(*v1alpha1.Tests) (*v1alpha1.Tests, error)
	Update(*v1alpha1.Tests) (*v1alpha1.Tests, error)
	UpdateStatus(*v1alpha1.Tests) (*v1alpha1.Tests, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Tests, error)
	List(opts v1.ListOptions) (*v1alpha1.TestsList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Tests, err error)
	TestsExpansion
}

// testses implements TestsInterface
type testses struct {
	client rest.Interface
	ns     string
}

// newTestses returns a Testses
func newTestses(c *MioV1alpha1Client, namespace string) *testses {
	return &testses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tests, and returns the corresponding tests object, and an error if there is any.
func (c *testses) Get(name string, options v1.GetOptions) (result *v1alpha1.Tests, err error) {
	result = &v1alpha1.Tests{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("testses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Testses that match those selectors.
func (c *testses) List(opts v1.ListOptions) (result *v1alpha1.TestsList, err error) {
	result = &v1alpha1.TestsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("testses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested testses.
func (c *testses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("testses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a tests and creates it.  Returns the server's representation of the tests, and an error, if there is any.
func (c *testses) Create(tests *v1alpha1.Tests) (result *v1alpha1.Tests, err error) {
	result = &v1alpha1.Tests{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("testses").
		Body(tests).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tests and updates it. Returns the server's representation of the tests, and an error, if there is any.
func (c *testses) Update(tests *v1alpha1.Tests) (result *v1alpha1.Tests, err error) {
	result = &v1alpha1.Tests{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("testses").
		Name(tests.Name).
		Body(tests).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *testses) UpdateStatus(tests *v1alpha1.Tests) (result *v1alpha1.Tests, err error) {
	result = &v1alpha1.Tests{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("testses").
		Name(tests.Name).
		SubResource("status").
		Body(tests).
		Do().
		Into(result)
	return
}

// Delete takes name of the tests and deletes it. Returns an error if one occurs.
func (c *testses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("testses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *testses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("testses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tests.
func (c *testses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Tests, err error) {
	result = &v1alpha1.Tests{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("testses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
