/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "hidevops.io/mioclient/pkg/apis/mio/v1alpha1"
	scheme "hidevops.io/mioclient/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TestConfigsGetter has a method to return a TestConfigInterface.
// A group's client should implement this interface.
type TestConfigsGetter interface {
	TestConfigs(namespace string) TestConfigInterface
}

// TestConfigInterface has methods to work with TestConfig resources.
type TestConfigInterface interface {
	Create(*v1alpha1.TestConfig) (*v1alpha1.TestConfig, error)
	Update(*v1alpha1.TestConfig) (*v1alpha1.TestConfig, error)
	UpdateStatus(*v1alpha1.TestConfig) (*v1alpha1.TestConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TestConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.TestConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestConfig, err error)
	TestConfigExpansion
}

// testConfigs implements TestConfigInterface
type testConfigs struct {
	client rest.Interface
	ns     string
}

// newTestConfigs returns a TestConfigs
func newTestConfigs(c *MioV1alpha1Client, namespace string) *testConfigs {
	return &testConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the testConfig, and returns the corresponding testConfig object, and an error if there is any.
func (c *testConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.TestConfig, err error) {
	result = &v1alpha1.TestConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("testconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TestConfigs that match those selectors.
func (c *testConfigs) List(opts v1.ListOptions) (result *v1alpha1.TestConfigList, err error) {
	result = &v1alpha1.TestConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("testconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested testConfigs.
func (c *testConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("testconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a testConfig and creates it.  Returns the server's representation of the testConfig, and an error, if there is any.
func (c *testConfigs) Create(testConfig *v1alpha1.TestConfig) (result *v1alpha1.TestConfig, err error) {
	result = &v1alpha1.TestConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("testconfigs").
		Body(testConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a testConfig and updates it. Returns the server's representation of the testConfig, and an error, if there is any.
func (c *testConfigs) Update(testConfig *v1alpha1.TestConfig) (result *v1alpha1.TestConfig, err error) {
	result = &v1alpha1.TestConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("testconfigs").
		Name(testConfig.Name).
		Body(testConfig).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *testConfigs) UpdateStatus(testConfig *v1alpha1.TestConfig) (result *v1alpha1.TestConfig, err error) {
	result = &v1alpha1.TestConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("testconfigs").
		Name(testConfig.Name).
		SubResource("status").
		Body(testConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the testConfig and deletes it. Returns an error if one occurs.
func (c *testConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("testconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *testConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("testconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched testConfig.
func (c *testConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestConfig, err error) {
	result = &v1alpha1.TestConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("testconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
